version: "3.8"

services:
  api:
    volumes:
      - ./volumes:/app/volumes
      - ../rue-api/app:/app/app
  worker:
    volumes:
      - ./volumes:/app/volumes
      - ../rue-api/app:/app/app
  flower:
    volumes:
      - ./volumes:/app/volumes
      - ../rue-api/app:/app/app
  api-dev:
    image: rue-api-dev:latest
    build:
      context: ../
      dockerfile: deployment/api/Dockerfile
      target: dev
    container_name: rue-api-dev
    ports:
      - "8000:8000"
      - "8001:22"
    env_file:
      - .env
    volumes:
      - ./volumes:/app/volumes
      - ../rue-api/app:/app/app
    depends_on:
      - worker